[package]
name = "nickel"
version = "0.1.0"
authors = ["Nicl team"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Programmable configuration files."
edition = "2018"

[features]
default = ["markdown", "repl"]
# markdown = ["termimad", "minimad", "lazy_static", "crossterm"]
markdown = ["termimad", "minimad"]
repl = ["rustyline"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.1"
either = "1.5.3"
simple-counter = "0.1.0"
codespan = "0.9.5"
codespan-reporting = "0.9.5"
logos = "0.11.4"
serde = "1.0.117"
serde_json = "1.0.59"
structopt = "0.3"
void = "1"

termimad = { version = "0.9.1", optional = true }
# Use the same version as termimad
minimad = { version = "0.6.7", optional = true }
# lazy_static = { version = "1.4", optional = true }
# crossterm = { version = "0.17.7", optional = true }

rustyline = {version = "7.1.0", optional = true}

[dev-dependencies]
pretty_assertions = "0.5.1"
