name: "Update rust channels"
on:
  schedule:
  - cron: '1 1 * * *'
jobs:

  update-channels:

    strategy:
      matrix:
        channel:
        - stable
        - beta
        - nightly

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Add `unstable` Nix channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing nixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    # - uses: cachix/cachix-action@v8
    #   with:
    #     name: nickel
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Update `${{ matrix.channel }}` channel
      run: |
        bash ./scripts/update_channel.sh ${{ matrix.channel }}

    - name: Build Nickel for `${{ matrix.channel }}` channel
      run: |
        nix build ./#packages.x86_64-linux.nickel_against_${{ matrix.channel }}_rust

    - name: Commit `scripts/channel_${{ matrix.channel }}.toml`
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update for `${{ matrix.channel }}` rust channel [ci skip]'
        branch: 'master'
        file_pattern: scripts/channel_${{ matrix.channel }}.toml
        commit_user_name: ???
        commit_user_email: ???
        commit_author: GitHub Actions <???>
      if: github.repository == 'tweag/nickel'
