name: "Build Nickel"
on: pull_request
jobs:

  build-nickel:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Add `unstable` Nix channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing nixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - uses: cachix/cachix-action@v8
      with:
        name: nickel

    - name: Build Nickel
      run: |
        nix build ./#packages.x86_64-linux.build

    - name: Run Makam Spec
      run: |
        nix build ./#checks.x86_64-linux.specs
