name: "Update the Nickel WASM REPL"
on:
  push:
    branches:
      - master

jobs:

  update-wasm-repl:

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nickel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build the Nickel WASM REPL
      run: |
        nix build ./#buildWasm
    - name: Update the nickel-repl node package
      run: |
        rm -rf website/nickel-repl
        cp -r result/nickel-repl website/

    - name: Commit update of the Nickel WASM REPL
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[auto]Update the Nickel WASM REPL [ci-skip]'
        branch: 'master'
        file_pattern: website/nickel-repl
        # See https://github.community/t/github-actions-bot-email-address/17204/6
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
      if: github.repository == 'tweag/nickel'
